name: PlatformIO Build

on:
  workflow_dispatch:  # Manuelles Auslösen über GitHub Web-Interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Run PlatformIO build
        run: pio run
