name: Build and Release ESP32 Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Upload all firmware artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .pio/build/*/firmware.bin
            .pio/build/*/bootloader.bin
            .pio/build/*/partitions.bin
            .pio/build/*/boot_app0.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
