name: PlatformIO Build & Release

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

on:
  push:
    tags:
      - 'v*'       # z. B. v1.0, v1.1.2 löst Workflow aus
  workflow_dispatch:  # Manuell in GitHub startbar

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Release Firmware

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run PlatformIO Build
        run: platformio run

      - name: Rename firmware binary
        run: |
          mkdir -p dist
          cp .pio/build/esp32dev/firmware.bin dist/firmware-${{ github.ref_name }}.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/firmware-${{ github.ref_name }}.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
